### ISSUE TITLE
Python 3.10 support?

### ISSUE THREAD

**Issue by borice** [jmcarpenter2/swifter#168]
I am trying to install swifter via `conda` in a new virtual environment based on Python 3.10 and it fails with some dependency issues.  Is Python 3.10 not supported, or perhaps something else is going on with my environment?

Thank you.

**Comment by charlie-ochoa** [comment]
Hi @borice, you're right, I believe there's no support for Python 3.10, I just had the same problem.
It would be nice some support added.

**Comment by jmcarpenter2** [comment]
This should be resolved now by #172 .

Please give it a go and let me know if you can install for Python 3.10 now :)

**Comment by borice** [comment]
I'm still not able to install via `conda`, but it works if I install via `pip`.

```
(testpy310) capitanu@leo:~$ conda install -c conda-forge swifter
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - swifter -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0']

Your python: python=3.10

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
```

Perhaps the newest swifter release hasn't made it to conda-forge yet...

**Comment by jmcarpenter2** [comment]
Hey @borice thanks so much for the  quick response! 

Yeah let's wait and see tomorrow. I'll try installing via conda tomorrow morning and if it still doesn't work I'll deep dive into why it's not propagating. But the dependency issues should be resolved

**Comment by jmcarpenter2** [comment]
Update: 
- I put up a pull request with conda-forge here https://github.com/conda-forge/staged-recipes/pull/17950#issuecomment-1030707233 to try to understand what actions are necessary to propagate the pypi release to conda-forge. This is typically an automatic process.

- As a temporary solution, I also uploaded it to my personal conda channel, which you can install using `conda install -c jmcarpenter2 swifter`. But that is NOT the official `conda-forge` channel and I would only recommend using it if absolutely necessary. Preferable would be to wait for conda-forge to update it on their official package channel.

**Comment by bnavigator** [comment]
Hi, I think it is worth mentioning, that dask is not available for Python 3.10 yet: https://github.com/dask/dask/pull/8566
That might explain your resolution issues.

**Comment by borice** [comment]
It works!

```
$ conda install -c conda-forge swifter
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/local/anaconda3/envs/dataspell

  added / updated specs:
    - swifter


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    swifter-1.1.2              |     pyhd8ed1ab_0          15 KB  conda-forge
    ------------------------------------------------------------
                                           Total:          15 KB

The following packages will be UPDATED:

  swifter            conda-forge/osx-64::swifter-1.0.9-py3~ --> conda-forge/noarch::swifter-1.1.2-pyhd8ed1ab_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
swifter-1.1.2        | 15 KB     | ############################################################################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

**Comment by jmcarpenter2** [comment]
Thanks @borice !
